### ISSUE TITLE
Devestator bardbot mac  error 2

### ISSUE THREAD

**Issue by aspire2008** [MMOBugs/MMOBugs-Macros#2]
Applied the fix from the previous issue ticket, and now the following error occurs.

Bards - [2018/12/08 13:33:44] No such 'auratype' member 'Equal'
Bards - [2018/12/08 13:33:44] bardbot.mac@197 (main(string iniNameStr)): /if (${Me.Aura[1].Equal[${auraSong}]} || ${Me.Aura[2].Equal[${auraSong}]} || ${Me.Aura[1].Equal[${auraText}]} || ${Me.Aura[2].Equal[${auraText}]}) {
Bards - [2018/12/08 13:33:44] Usage: /call <subroutine> [param [param...]]
Bards - [2018/12/08 13:33:44] Usage: /call <subroutine> [param [param...]]
Bards - [2018/12/08 13:33:44] Usage: /call <subroutine> [param [param...]]
Bards - [2018/12/08 13:33:44] Usage: /call <subroutine> [param [param...]]
Bards - [2018/12/08 13:33:44] Usage: /call <subroutine> [param [param...]]
Bards - [2018/12/08 13:33:44] Usage: /call <subroutine> [param [param...]]
Bards - [2018/12/08 13:33:44] Usage: /call <subroutine> [param [param...]]
Bards - [2018/12/08 13:33:44] Usage: /call <subroutine> [param [param...]]
Bards - [2018/12/08 13:33:44] Usage: /call <subroutine> [param [param...]]
Bards - [2018/12/08 13:33:44] Usage: /call <subroutine> [param [param...]]
Bards - [2018/12/08 13:33:44] Usage: /call <subroutine> [param [param...]]

**Comment by htwmmo** [comment]
Fixed this, core returns false (no such member) if an aura doesn't exist, instead of just returning true (valid member), but empty.  Fixed this in our release, and it's currently live, you shouldn't see it complaining about this particular issue any longer.

**Comment by aspire2008** [comment]
Still seem to be having this issue when I start up the macro, but now the issue is as follows:

`
Bardo - [2018/12/20 11:45:05] No such 'auratype' member 'Equal'
Bardo - [2018/12/20 11:45:05] bardbot.mac@197 (main(string iniNameStr)): /if (${Me.Aura[1].Equal[${auraSong}]} || ${Me.Aura[2].Equal[${auraSong}]} || ${Me.Aura[1].Equal[${auraText}]} || ${Me.Aura[2].Equal[${auraText}]}) {
Bardo - [2018/12/20 11:45:05] No such 'auratype' member 'Equal'
Bardo - [2018/12/20 11:45:05] bardbot.mac@197 (main(string iniNameStr)): /if (${Me.Aura[1].Equal[${auraSong}]} || ${Me.Aura[2].Equal[${auraSong}]} || ${Me.Aura[1].Equal[${auraText}]} || ${Me.Aura[2].Equal[${auraText}]}) {
Bardo - [2018/12/20 11:45:05] Usage: /call <subroutine> [param [param...]]
Bardo - [2018/12/20 11:45:05] Usage: /call <subroutine> [param [param...]]
Bardo - [2018/12/20 11:45:05] Usage: /call <subroutine> [param [param...]]
Bardo - [2018/12/20 11:45:05] Usage: /call <subroutine> [param [param...]]
Bardo - [2018/12/20 11:45:05] Usage: /call <subroutine> [param [param...]]
Bardo - [2018/12/20 11:45:05] Usage: /call <subroutine> [param [param...]]
Bardo - [2018/12/20 11:45:06] devCommonPremium.inc@1998 (buffCheckRoutine(string checkTypes, bool combatBuff, string onCallRoutine)): /if (${Me.Aura[1].Name.Equal[${buffText[${nArray}]}]} || ${Me.Aura[1].Name.Equal[${buffName[${nArray}]}]} || ${Me.Aura[2].Name.Equal[${buffText[${nArray}]}]} || ${Me.Aura[2].Name.Equal[${buffName[${nArray}]}]}) {
Bardo - [2018/12/20 11:45:06] devCommonPremium.inc@1642 (buffCheck(bool useTimer, bool combatBuff, string onCallRoutine)): /call buffCheckRoutine ${checkTypes} ${combatBuff} ${onCallRoutine}
Bardo - [2018/12/20 11:45:06] bardbot.mac@204 (main(string iniNameStr)): /if (!${minBuffCheckTimer}) /call buffCheck
Bardo - [2018/12/20 11:45:06] No such 'string' member 'Name'`

Whatever the change that was applied is happening on all my macros not just Dev's bots, happening on IHC bot macros that use aura's , as well as KissAssist macro that calls auras in buffcheck routine.  This wasn't the case before the new fix.  The former error in the original post only occurred in Dev's bot, but with the new fix its doing the "No such string member Name" for all macros I'm currently using, which are all non-devbot macros.


Also, the "Usage /call subroutine param param , might be a different issue in regards to custom ini names when you start the macro i.e. /mac bardbot "custominifilename"
